M48
; DRILL file {KiCad 7.0.7} date Thu Feb 22 14:53:58 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-22T14:53:58+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.1969Y-0.1969
X0.1969Y-4.8031
X7.3031Y-0.1969
X7.3031Y-4.8031
T0
M30
